NewAcropolis/api

- app/__init__.py
- app/errors.py
- app/events/rest.py
- app/fees/rest.py
- app/fees/schemas.py
- app/schema_validation/__init__.py
- requirements.txt
- tests/app/fees/test_rest.py
Added - 
- Fee REST endpoint 
>- create and get all fees
- Schema for fees
- Page error handling
> Add schema and fees rest

- app/__init__.py
> Added timestamps for logging

- app/__init__.py
- run_app.sh
Update logging to improve output
> Refactor logging

- .gitignore
- app/__init__.py
- tests/app/fees/test_rest.py
- Removed redundant print in test
- Removed default log handlers to make log output clearer
> Remove default log handlers

- app/__init__.py
- app/fees/rest.py
Allows fees to be accessed via id
> Add get fee id rest

- app/__init__.py
- app/dao/event_types_dao.py
- app/event_types/rest.py
- app/event_types/schemas.py
- app/fees/rest.py
- app/fees/schemas.py
- app/models.py
- app/schema_validation/definitions.py
- tests/app/event_types/test_rest.py
- tests/app/fees/test_rest.py
- update fees 
- added event_types
- added fee validation
> Add event type rest

- app/dao/fees_dao.py
- app/models.py
- migrations/versions/0001.py
- migrations/versions/0002.py
- tests/app/dao/test_event_types_dao.py
- tests/app/test_models.py
- tests/db.py
As valid_from will be populated from StartDate it seems more appropriate than created_at
> Change created_at to valid_from

- .gitignore
- app/__init__.py
- app/authentication/errors.py
- app/authentication/rest.py
- app/authentication/schemas.py
- app/config.py
- app/errors.py
- app/event_types/rest.py
- app/fees/rest.py
- requirements.txt
- test_auth.sh
- tests/app/authentication/test_rest.py
- tests/app/event_types/test_rest.py
- tests/app/fees/test_rest.py
- tests/conftest.py
> Add flask jwt extended

- .travis.yml
- app/authentication/errors.py
- app/authentication/rest.py
- app/errors.py
- deploy.sh
- run_app.sh
- test_auth.sh
- tests/app/authentication/test_rest.py
- added ADMIN_CLIENT_ID & ADMIN_CLIENT_SECRET env vars
- improved run_app to activate venv
> Fix deploy of authenticated endpoints

- app/__init__.py
- app/config.py
- app/rest.py
- check_site.sh
- deploy.sh
- tests/app/test_rest.py
In order to ensure that the website is running after deployment an additional endpoint has been added that shows the migration script number. 
- it will fail deployments if after 5 retries of 10 second delays occur.
> Add check that website is deployed and connected to database

- app/models.py
- migrations/versions/0006.py
- tests/app/test_models.py
> Alter Speaker model with alternate_names

- app/dao/event_types_dao.py
- app/dao/events_dao.py
- app/dao/fees_dao.py
- app/dao/speakers_dao.py
- app/routes/event_types/rest.py
- app/routes/fees/rest.py
- app/routes/speakers/rest.py
- tests/app/dao/test_event_types_dao.py
- tests/app/dao/test_events_dao.py
- tests/app/dao/test_fees_dao.py
- tests/app/dao/test_speakers_dao.py
- fees
- event_types
- events
- speakers
> Refactor daos

- app/dao/event_types_dao.py
- app/models.py
- app/routes/event_dates/rest.py
- app/routes/event_types/rest.py
- app/routes/event_types/schemas.py
- app/routes/fees/rest.py
- app/schema_validation/definitions.py
- integration_test.sh
- tests/app/dao/test_event_types_dao.py
- tests/app/routes/event_dates/test_rest.py
- tests/app/routes/event_types/test_rest.py
- tests/app/routes/fees/test_rest.py
affects - event_dates, event_types, fees
Add import event_types
> Remove data element from json, and add import event_types

- app/schema_validation/__init__.py
- app/schema_validation/definitions.py
- tests/app/routes/event_dates/test_rest.py
Added string_is_number for formatting as in some cases the value can be `null` but this isn't handled properly.
> Add string_is_number format function

- Makefile
- README.md
Added 'make dependecies' in the makefile to install requirements
Refered to the knew make command in README.md
Added other useful information to help with setup
> Updated README.md and makefile to help with setup

- README.md
- app/routes/__init__.py
- app/routes/events/rest.py
- integration_test.sh
- tests/app/routes/test_routes.py
Prevents import of images from remote server and update the README to include information about imports.
> Only import images locally

- app/errors.py
- app/models.py
- tests/app/test_models.py
Also improve logging of DecodeErrors
> Clean article summary

- integration_test.sh
- requirements.txt
- scripts/run_app.sh
Increase timeout to 240 seconds and use gevent async processing to handle requests by gunicorn
> Update gunicorn config

- app/routes/events/rest.py
- app/routes/events/schemas.py
- app/schema_validation/definitions.py
- app/storage/utils.py
- integration_test.sh
- tests/app/routes/events/test_rest.py
- tests/app/storage/test_utils.py
- tests/conftest.py
Enable upload of event images onto google storage and update the integration_test.sh to test event creation.
> Add upload event image

- app/routes/events/rest.py
- tests/app/routes/events/test_rest.py
- tests/db.py
Improves handling of speakers with simpler code and adds a more complicated tests for an event with multiple dates and speakers
> Fix event dates speakers

- app/routes/events/rest.py
- tests/app/routes/events/test_rest.py
Updated to make it more robust when an image doesn't exist
Also updated events test to make them more stable
> Update import events

- app/routes/events/rest.py
- tests/app/routes/events/test_rest.py
This PR also improves the paypal comparison to avoid the paypal api call which can take a while.
> Update image filename to match generated one

- app/models.py
- app/routes/events/rest.py
- tests/app/routes/events/test_rest.py
- should improve comparisson to prevent multiple dates from being created
> Update the serialized event date to drop seconds

- app/routes/speakers/rest.py
- tests/app/routes/speakers/test_rest.py
> Returns speaker if found during creation

- app/comms/email.py
- app/payments/paypal.py
- tests/app/comms/test_email.py
- tests/app/payments/test_paypal.py
- allows api to run even withot paypal and email configs
> Add code to handle missing config

- app/__init__.py
- requirements.txt
- scripts/bootstrap.sh
Also update google storage to use latest google core
> Fix google cloud logging

- app/routes/emails/rest.py
- integration_test.sh
- tests/app/routes/emails/test_rest.py
> Add get email_types

- app/comms/email.py
- app/routes/emails/rest.py
- app/routes/emails/schemas.py
- integration_test.sh
- tests/app/routes/emails/test_rest.py
Add send_email response to update email rest and add email integration tests.
> Add email response

- app/__init__.py
- app/config.py
- app/dao/__init__.py
- app/dao/event_dates_dao.py
- app/dao/orders_dao.py
- app/dao/tickets_dao.py
- app/models.py
- app/routes/orders/rest.py
- migrations/versions/0032.py
- requirements_tests.txt
- scripts/deploy.sh
- tests/app/dao/test_event_dates_dao.py
- tests/app/routes/orders/test_rest.py
- tests/conftest.py
Note - using Sandbox account, will need to switch to live account before release
> Add orders and tickets

- app/config.py
- scripts/deploy.sh
Also log errors on debug set in travis
> Fix deploy email tokens

- app/config.py
- app/storage/utils.py
- app_start.py
- requirements.txt
- tests/app/storage/test_utils.py
Also generate web images when uploading an image
> Add generate web_images

- app/__init__.py
As using google-fluentd to capture logs because it is already set up to capture logs for celery
> Remove setup_gce_logging

- app/rest.py
- requirements.txt
- scripts/check_site.sh
- scripts/run_celery.sh
- scripts/run_local_celery.sh
- tests/app/test_rest.py
Check that celery workers are running and update pillow to mitigate security concerns.
> Check workers

- app/__init__.py
- app/utils/storage.py
Use config as celery has problems getting the correct env vars.
> Use app config, not environ for settings

- app/comms/email.py
- app/config.py
- tests/app/comms/test_email.py
- tests/app/routes/events/test_rest.py
- tests/app/routes/legacy/test_rest.py
- tests/app/routes/magazines/test_rest.py
- tests/conftest.py
Disable emails, useful for running the stack locally when you don't need to look at emails
Also update the conftest with GA_ID and tests that use it
> Add EMAIL_DISABLED flag to prevent sending emails

- app/comms/email.py
- app/dao/emails_dao.py
- app/dao/users_dao.py
- app/routes/events/rest.py
- tests/app/dao/test_emails_dao.py
> Fix emails

- app/comms/email.py
- app/na_celery/email_tasks.py
- app/routes/members/rest.py
- app/templates/emails/basic.html
- tests/app/routes/members/test_rest.py
Add stats for member subscription and unsubscription
Also always send unsub code for public emails
> Add ga events members

- app/config.py
Update max size to 1500 x 800, instead file image size will be controlled on the frontend side
> Update max size

- app/routes/orders/rest.py
- tests/conftest.py
> Revert "Allow TEST_VERIFY on live temporarily"

- .github/workflows/ci.yml
> Revert "Update ci.yml to allow IPN replay"

- .github/workflows/ci.yml
coveralls down for maintenance so don't submit to coveralls in meantime
> Comment out coveralls

- app/routes/orders/rest.py
- tests/app/routes/orders/test_rest.py
and set original TXN_ID after IPN replay
> Update get orders for invalid orders

- app/config.py
- app/routes/orders/rest.py
- tests/app/routes/orders/test_rest.py
- tests/conftest.py
Use receiver id for checking instead
> Handle no receiver_email
